language: python
sudo: false

install:
  - pip install tox, codecov

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27-twcurrent
  - TOX_ENV=pypy-twcurrent
  - TOX_ENV=py27-twtrunk
  - TOX_ENV=py33-twtrunk
  - TOX_ENV=py34-twtrunk
  - TOX_ENV=pypy-twtrunk

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  - codecov

notifications:
   irc:
      channels:
         - "irc.freenode.org#crossbar"
      use_notice: true
      skip_join: true
