language: python
sudo: false

install:
  - pip install tox

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27twisted
  - TOX_ENV=pypy2twisted

script:
  - tox -c tox.ini -e $TOX_ENV

notifications:
   irc:
      channels:
         - "irc.freenode.org#crossbar"
      use_notice: true
      skip_join: true
