name: docker

on:
  # Trigger this workflow when the "main" workflow has completed successfully
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows:
      - deploy
    branches:
      - master
    types:
      - completed

jobs:

  image_amd64:

    #runs-on: ubuntu-20.04
    runs-on: [self-hosted, linux, ARM64] # means matterhorn

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: Set environment
      run: |
        echo CROSSBAR_BUILD_DATE=`date -u +"%Y-%m-%d"` >> $GITHUB_ENV
        echo CROSSBAR_VCS_REF=`git rev-parse --short ${GITHUB_SHA}` >> $GITHUB_ENV
        echo CROSSBAR_BUILD_ID=$(date --utc +%Y%m%d)-$(git rev-parse --short ${GITHUB_SHA}) >> $GITHUB_ENV
        echo CROSSBAR_VERSION=$(grep -E '^(__version__)' ./crossbar/_version.py | cut -d ' ' -f3 | sed -e 's|[u"'\'']||g') >> $GITHUB_ENV

    - name: Print environment
      run: |
        echo ""
        echo "Build environment configured:"
        echo ""
        echo "  CROSSBAR_BUILD_DATE = ${CROSSBAR_BUILD_DATE}"
        echo "  CROSSBAR_BUILD_ID   = ${CROSSBAR_BUILD_ID}"
        echo "  CROSSBAR_VCS_REF    = ${CROSSBAR_VCS_REF}"
        echo "  CROSSBAR_VERSION    = ${CROSSBAR_VERSION}"
        echo ""

    - name: Build & publish Docker image for cpy-amd64
      run: |
        cd ./docker && \
        make download_wheels && \
        make build_amd64_cpy3 && \
        pwd && ls -la . && \
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io && \
        make publish_amd64_cpy3

    - name: Build & publish Docker image for pypy-amd64
      run: |
        cd ./docker && \
        make download_wheels && \
        make build_amd64_pypy3 && \
        pwd && ls -la . && \
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io && \
        make publish_amd64_pypy3
